name: VolleyballUPDATE
version: '1.4'
main: ru.ienumerable.volleyball.Volleyball
api-version: '1.19'
authors: [ NeoVai ]
commands:
  ballskin:
    description: sets ball skin
    usage: /ballskin
  ballsreload:
    description: reload balls config
    usage: /ballsreload
    permission: volleyball.reload
  ballsummon:
    description: summon new ball
    usage: /ballsummon <x> <y> <z> <world>
    permission: volleyball.summon